# Generated by Django 3.0.3 on 2020-02-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.TextField()),
                ('TelephoneNumber', models.IntegerField()),
                ('Country', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
        ),
    ]
