# Generated by Django 3.0.3 on 2020-02-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='CreatedAt',
        ),
    ]
