# Generated by Django 2.2.9 on 2020-02-18 01:09

import datetime
from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('dueDate', models.DateField(default=services.models.Timetables.return_date_time)),
                ('exams', models.TextField(default='')),
                ('accessCode', models.TextField(default='')),
                ('orgId', models.IntegerField(default=0)),
            ],
        ),
    ]
