# Generated by Django 2.2.9 on 2020-06-05 00:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetables',
            fields=[
                ('startDate', models.DateField(default=datetime.date.today)),
                ('dueDate', models.DateField(default=services.models.Timetables.return_date_time)),
                ('exams', models.TextField(default='')),
                ('accessCode', models.TextField(default='', primary_key=True, serialize=False)),
                ('time_slots', models.TextField(default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
