# Generated by Django 2.2 on 2020-02-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cc',
            field=models.PositiveIntegerField(verbose_name='cc'),
        ),
    ]
