# Generated by Django 2.2 on 2020-02-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cc',
            field=models.PositiveSmallIntegerField(verbose_name='cc'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
